### ISSUE TITLE
Clarify language surrounding Reference Client

### ISSUE THREAD

**Issue by shahankhatch** [EntEthAlliance/EntEthVision#4]
When referring to a single client as the reference client, in this case the Python client, there is a risk that a standard's implementation within that reference client may be interpreted as the de facto standard, when in reality there may be many implementations. 

In order to give multiple implementations an opportunity to play a role in EEA standards, a suggestion is to rename the reference client to a _research_ client.

**Comment by chaals** [comment]
We didn't end up with a "definitive" client of any kind. Closing.
